-function(){"use strict";var g;var h={i:function(a,b){var d=h.c();d&&d.saveStyleOverride(this,a,b);this.style[a]=b},f:function(a,b){b?this.classList.add(a):this.classList.remove(a)},v:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.textContent=a;b&&b.applyStylePreservation(this)}},u:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.innerHTML=a;b&&b.applyStylePreservation(this)}},show:function(a){this.style.display=a?"":"none"},setAttribute:function(a,b){this.setAttribute(a,
b)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=h;h.setText=h.v;h.setStyle=h.i;h.setHtml=h.u;h.addOrRemoveClassName=h.f;h.show=h.show;h.setAttribute=h.setAttribute;var m={limit:function(a,b){return b?a&&a.length&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},pluck:function(a,b){if(a){var d=b.split(".");return a.map(function(a){if(1==d.length)return a[d[0]];var b=a;d.forEach(function(a){b&&(b=b[a])});return b})}return[]},join:function(a,b){return a?a.join(b||","):""},s:function(a,b){return m.join(m.pluck(a,b))},toUpperCase:function(a){return a?a.toUpperCase():a},toLowerCase:function(a){return a?a.toLowerCase():a},A:function(a){if("undefined"!=
typeof a)return a+"px"},w:function(a){return a?a.replace(/0x/,"#"):a}};window.Formatter=m;m.limit=m.limit;m.toUpperCase=m.toUpperCase;m.toLowerCase=m.toLowerCase;m.toPixelValue=m.A;m.toHex=m.w;m.pluck=m.pluck;m.join=m.join;m.pluckAndJoin=m.s;var n=/^bind-/,p=/^style-/,q=/^class-/,r=/^each-/,t=/\/-([a-z])\/g/;function u(a){return String(a).replace(t,function(a,d){return d.toUpperCase()})}function w(a){return!(!a||!n.test(a.name))}function x(a){return!(!a||0!=a.name.indexOf("bind-each"))}function y(a){Array.prototype.slice.call(a.attributes).filter(x).forEach(function(b){a.removeAttribute(b.name)})}var z=function(){};goog.inherits(z,HTMLElement);g=z.prototype;
g.createdCallback=function(){this.a={text:"setText",html:"setHtml",show:"show"};this.b={limit:"limit",pixelvalue:"toPixelValue",uppercase:"toUpperCase",lowercase:"toLowerCase",hex:"toHex",pluck:"pluck",join:"join",pluckandjoin:"pluckAndJoin"};this.h=!1};g.getBinder=function(){return h};g.getFormatter=function(){return m};
g.bindData=function(a,b){var d=b||Array.prototype.slice.call(document.querySelectorAll("*")),f=document.querySelector("meta[name=environment]");this.h="gwd-adwords"==(f?f.getAttribute("content"):"");d.forEach(this.j.bind(this,a))};g.j=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var d,f=Array.prototype.slice.call(b.attributes),e=f.length,c=0;c<e;c++)if(x(f[c])){d=f[c];break}e=this.m.bind(this,b,a);d?e(d):f.filter(w).forEach(e)}};
g.m=function(a,b,d){var f=d.name,e=f.replace(n,""),c;c=this.getBinder();if(p.test(e)){var l=e.replace(p,"");c=c.i.bind(a,u(l))}else q.test(e)?(l=e.replace(q,""),c=c.f.bind(a,l)):r.test(e)?(c=e.replace(r,""),c=this.l.bind(this,a,c,b)):c=this.a[e]&&"function"==typeof c[this.a[e]]?c[this.a[e]]:window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[e]?window.gwd.binders[e]:c.setAttribute.bind(a,e);f=a.getAttribute(f);b=(-1!==f.indexOf("|")?this.o.bind(this,b,f):this.g.bind(this,b,f)).call(a);
this.h&&"exit-override-url"==e&&a.setAttribute("exit-id",d.value.replace(/\./g,"_"));c.apply(a,[b])};
g.l=function(a,b,d,f){var e=a.parentNode;if(e){var c=a.cloneNode(!0);y(c);for(var l=[],k=0;f&&k<f.length;k++)l.push(c.cloneNode(!0));k={instances:l};c=document.createEvent("CustomEvent");c.initCustomEvent("gwdbindeachcloned",!0,!0,k);a.dispatchEvent(c);c=document.createComment("gwd-bind-each-placeholder");e.insertBefore(c,a);e.removeChild(a);A(a);if(f&&0!=f.length){for(var v,k=0;k<f.length;k++)d[b]=f[k],a=l[k],a.setAttribute("gwd-repeat-index",k),d.$index=k,v=Array.prototype.slice.call(a.querySelectorAll("*")),
this.bindData(d,v.concat(a)),e.insertBefore(a,c);delete d[b]}}};var A=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(a){a.setAttribute("gwd-bind-each-template","")})};z.prototype.g=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var d=a;b.split(".").forEach(function(a){d&&(d=d[a])});return d}return a}return null};
z.prototype.o=function(a,b){if(b){for(var d=b.split("|"),f=d.shift().trim(),f=this.g(a,f),e;0<d.length;){e=d.shift().trim();e=e.split(" ");var c=e.shift().trim();e.unshift(f);var l=this.getFormatter(),f=this.b[c]&&"function"==typeof l[this.b[c]]?l[this.b[c]].apply(this,e):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[c]?window.gwd.formatters[c].apply(this,e):f}return f}return a};z.prototype.attributeChangedCallback=null;document.registerElement("gwd-data-binder",{prototype:z.prototype});}()
