+function(){var g;var k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},l=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null},n=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},p=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},w=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var y=function(a,b){return a.x*b.x+a.y*b.y},B=function(a,b){return z(b,y(a,b))},z=function(a,b){return C(a.x*b,a.y*b)},C=function(a,b){return{x:a,y:void 0!==b?b:a}};var D=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ea=function(a,c,f){for(var m=Array(arguments.length-2),q=2;q<arguments.length;q++)m[q-2]=arguments[q];return b.prototype[c].apply(a,m)}};var F=["-ms-","-moz-","-webkit-",""],G=function(a,b,c){for(var d,e,f=0;f<F.length;++f)d=F[f]+b,e=""+c,a.style.setProperty(d,e)};var H=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},aa=function(a,b){setTimeout(function(){H("autoplayended",a,b)},0)},ba=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var ca=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var da=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},J=function(a,b){this.m=a;this.s=null;this.Da=b;this.L=!1};
J.prototype.play=function(a,b,c){if(this.m.frameCount&&null==this.s){b=b||"forwards";var d;c?(d=Math.floor(a/c),a=c):(d=this.m.frameCount,a/=d);var e=[],f=da(this.m);c=f;for(var m=0;m<d;m++){if(0<m||!this.Da)c=K(c+L(b,1),this.m.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.L=!0;this.m.goToFrame(a+1);this.L=!1;var b=this.m;H("frameautoplayed",b,{id:a+1||b.currentIndex})}else this.stop(!0),this.m.goToFrame(f+1)}.bind(this);this.s=setInterval(b,a);setTimeout(b)}};
J.prototype.stop=function(a){!this.L&&this.s&&(clearInterval(this.s),aa(this.m,{completed:!!a}),this.s=null)};
var ea=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},M=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(ea(ca(a[c])))}return b},N=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},fa=function(a,b){for(var c=b.length,d=b.splice(0,c),e,f=0;f<c;f++)e=d[f],"frameshown"==
e?H(e,a,{id:a.currentIndex}):H(e,a)},L=function(a,b){return"left"==a||"backwards"==a?-b:b},K=function(a,b){return(a%b+b)%b},ga=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})},ha=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.play()})};var O=function(){};D(O,HTMLElement);g=O.prototype;g.createdCallback=function(){this.frames=[];this.a=null;this.b=0;this.l=1;this.v=new J(this,!0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.ma.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.pa.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.oa.bind(this)});this.fa=this.hasAttribute("pause-front-media");this.ga=this.hasAttribute("resume-next-media")};
g.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.fa=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.ga=this.hasAttribute("resume-next-media")}};g.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};g.gwdLoad=function(){};g.gwdIsLoaded=function(){return!0};g.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.Y(a,b))};g.Y=function(a){this.a=a-1};
var P=function(a,b,c,d){if(null!=a.a){var e=K(a.a+L(b,a.l||1),a.l*Math.ceil(a.b/a.l));((null!=d?d:1)||!("forwards"==b&&e<a.a||"backwards"==b&&e>a.a))&&a.goToFrame(e+1,c||"slide")}};g=O.prototype;g.goBackwards=function(a,b){return P(this,"backwards",a,b)};g.goForwards=function(a,b){return P(this,"forwards",a,b)};g.rotateOnce=function(a,b){this.v.play(a||0,b)};g.stopRotation=function(){this.v.stop()};g.ma=function(){return 0<this.b?this.a+1:void 0};g.pa=function(){return this.l};g.oa=function(){return this.b};var Q=function(){};D(Q,O);
Q.prototype.createdCallback=function(){Q.B.createdCallback.call(this);this.M=!1;this.N=this.c=null;if(this.X=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.o=C(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.K=a;this.j=!1;this.f=null;this.ba=this.wa.bind(this);this.da=this.ya.bind(this);this.$=this.ua.bind(this);this.aa=this.va.bind(this);this.ca=this.xa.bind(this);this.U=this.ra.bind(this);this.la=this.Ba.bind(this);this.ka=this.Aa.bind(this);
this.ja=this.za.bind(this);this.W=this.sa.bind(this);this.ea=this.ta.bind(this);this.G=H.bind(null,"firstinteraction",this);this.R=!1;this.P=[];this.u=fa.bind(null,this,this.P);this.ha=this.ia=this.D=this.T=this.S=0;this.J=1;this.F=[];this.I=0;this.Ca=.7;this.A=0;this.C=!1;this.O=C(0);this.H=C(0);this.g=null;this.h=this.Z=-1;this.V=[];this.w=C(-1,-1);a="y"==this.getAttribute("swipe-axis");this.i=C(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.na.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.qa.bind(this)})};
Q.prototype.attachedCallback=function(){var a=this.K;a.addEventListener("pointerover",this.da,!1);a.addEventListener("pointerout",this.ba,!1);a.addEventListener("pointermove",this.$,!1);a.addEventListener("track",this.la,!1);a.addEventListener("trackend",this.ka,!1);a.addEventListener("tap",this.ja,!1);this.addEventListener("frametap",this.W,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",this.u,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&
!this.gwdIsLoaded()){var b=(a=l(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
Q.prototype.detachedCallback=function(){var a=this.K;a.removeEventListener("pointerover",this.da,!1);a.removeEventListener("pointerout",this.ba,!1);a.removeEventListener("pointermove",this.$,!1);a.removeEventListener("track",this.la,!1);a.removeEventListener("trackend",this.ka,!1);a.removeEventListener("tap",this.ja,!1);this.removeEventListener("frametap",this.W,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",this.u)};
Q.prototype.attributeChangedCallback=function(a){Q.B.attributeChangedCallback.call(this,a);switch(a){case "images":this.frames=M(this.getAttribute("images"));R(this);S(this);break;case "scaling":N(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":T(this);S(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":U(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":U(this);
S(this);break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":S(this)}};
var U=function(a){var b=n(a,"num-frames-to-display",1),c=n(a,"frame-snap-interval",1),d=n(a,"transition-duration",600),e=n(a,"frame-width",-1),f=n(a,"frame-height",-1),m;m=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"";var q=p(a,"autoplay-duration",3E3),r=p(a,"autoplay-step-interval",0);a.w.x=e;a.w.y=f;-1!=y(a.w,a.i)?b=-1:0<b&&c>b&&(c=b);a.V=m.split(/,/g);a.h=b;a.l=c;a.D=d;a.S=q;a.T=r},S=function(a){var b,c,d=C(a.clientWidth,a.clientHeight);a.g&&(d.y-=36,a.N.style.height=d.y+"px");var e=
a.i,f=z(e,n(a,"offset",0)),m=p(a,"swipe-threshold-ratio",.1),q=p(a,"swipe-committed-threshold-ratio",.5),r=a.h,h=a.w,h=C(-1==h.x?d.x:h.x,-1==h.y?d.y:h.y);if(a.hasAttribute("offset")){a:{b=h.x;c=h.y;var u;b:switch(a.getAttribute("clamp-frame-size-to-image")){case "true":u=!0;break b;case "false":u=!1;break b;default:u=!0}if(u){var v;v=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain";if((u="contain"==v)||"none"==v){var E=-1;v=-1;for(var ia=a.frameCount,I=0;I<ia;I++){var t=a.getFrame(I+
1);if("img"!=t.tagName.toLowerCase()||"gwd-image"!=t.getAttribute("is"))break a;var x=t,t=x.assetWidth,A=x.assetHeight;0<t&&0<A&&(u?t/A<b/c?(x=t/A*c,t=c):(x=b,t=A/t*b):(x=t,t=A),E=Math.max(E,x),v=Math.max(v,t))}b=-1!=E?Math.min(b,E):b;c=-1!=v?Math.min(c,v):c}}}1==e.x?h.x=b:h.y=c}1<r&&(c=z(e,r-1),c=C(c.x*f.x,c.y*f.y),r=B(C((d.x-c.x)/r,(d.y-c.y)/r),e),r.x&&(h.x=r.x),r.y&&(h.y=r.y));r=n(a,"start-frame",2<a.h?1+Math.ceil(a.h/2-1):1);b=a.hasAttribute("disable-gesture");c=B(C(h.x+f.x,h.y+f.y),e);u=1+2*
Math.floor((y(e,d)-y(e,h))/(2*y(e,c)));if(1>u||!isFinite(u))u=1;d=C((d.x-h.x)/2,(d.y-h.y)/2);0<a.h&&0==a.h%2&&(f=B(C(h.x+f.x,h.y+f.y),e),d.x-=.5*f.x,d.y-=.5*f.y,u+=1);a.H=h;a.O=d;a.J=u;a.A=y(c,a.i);a.j=b;a.ia=y(h,e)*m;a.ha=y(h,e)*q;m=B(d,C(e.y,e.x));for(f=0;f<a.b;f++)q=a.frames[f].style,q.left=m.x+"px",q.top=m.y+"px",q.width=h.x+"px",q.height=h.y+"px",m.x+=c.x,m.y+=c.y;a.o=C(0);a.c&&(V(a,0,0,0),e=B(d,e),a.c.style.left=e.x+"px",a.c.style.top=e.y+"px");a.a=null;a.goToFrame(r,"none")};g=Q.prototype;
g.gwdIsLoaded=function(){return this.M};g.gwdLoad=function(){if(!this.M&&!this.c){var a;if(this.X)a=M(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;R(this)}};g.goBackwards=function(a,b){return Q.B.goBackwards.call(this,a,null!=b?b:!1)};g.goForwards=function(a,b){return Q.B.goForwards.call(this,a,null!=b?b:!1)};
g.Y=function(a,b){var c=a-1,c=c-c%this.l,c=c+Math.floor((this.l-1)/2);c>=this.b&&(c=this.b-1);var d=c;null!=this.a&&this.a!=d&&(this.fa&&ga(this.frames[this.a]),this.ga&&ha(this.frames[d]));d=this.a;this.a=c;c=z(this.i,-this.A*this.a);V(this,"none"!=b?this.D:0,c.x,c.y);this.o=c;if(this.I)for(var c=Math.floor((this.J-1)/2),e=0;e<this.J;e++){var f=this.a-c+e;if(!(0>f||f>=this.b||this.F[f]||(this.F[f]=!0,--this.I))){this.P.push("allframesviewed");break}}d!=this.a&&(W(this,this.a+1),this.P.push("frameshown"));
this.R||this.u()};
var V=function(a,b,c,d){a.R=0<b;G(a.c,"transition","all "+b+"ms");G(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},R=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.g=null;a.c&&(a.c.removeEventListener("pageload",a.ea,!1),a.c.removeEventListener("mouseover",a.ca,!0),a.c.removeEventListener("mouseout",a.aa,!0),a.c.removeEventListener("click",a.U,!0));for(var b=a.frames,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],G(d,"user-select","none"),d.classList.add("frame"),
c.appendChild(d);ba(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.ea,!1);a.c.addEventListener("mouseover",a.ca,!0);a.c.addEventListener("mouseout",a.aa,!0);a.c.addEventListener("click",a.U,!0);N(a.frames,a.getAttribute("scaling"));a.b=a.frames.length;b=document.createElement("div");a.N=b;b.className="matte";b.appendChild(c);a.appendChild(a.N);a.appendChild(a.K)};
Q.prototype.ta=function(a){a.target===this.c&&(this.M=!0,this.I=this.b,this.F=[],U(this),T(this),S(this),H("allframesloaded",this),this.hasAttribute("autoplay")&&this.v.play(this.S,"forwards",this.T),H("ready",this))};Q.prototype.rotateOnce=function(a,b){this.v.play(a||this.D,b)};
var Y=function(a,b){var c=a.b;if(c){var d=a.a,e=X(a,b);a.goToFrame(e+1);d!=e&&(0==e?H("reachleftend",a):e==c-1&&H("reachrightend",a))}},T=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.g;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.g=document.createElement("gwd-gallerynavigation"),a.g.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.g)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.g),a.g=null);a.g&&(w(a,"navigation-highlight",a.g,"highlight"),
w(a,"navigation-thumbnails",a.g,"use-thumbnails"))},X=function(a,b){var c=a.a;Math.abs(b)>a.ia&&(c=0>b?c+a.l:c-a.l);0>c?c=0:c>=a.b&&(c=a.b-1);return c},W=function(a,b){a.Z!=b&&(a.Z=b,H("frameactivated",a,{id:b||a.currentIndex}))};
Q.prototype.Ba=function(a){if(!this.j&&(this.G&&(this.G(),this.G=null),!this.C))if(this.stopRotation(),a=y(C(a.dx,a.dy),this.i),W(this,X(this,a)+1),Math.abs(a)>this.ha)Y(this,a),this.C=!0;else{if(0<a&&0===this.a||0>a&&this.a===this.b-1)a-=a*this.Ca;V(this,0,this.o.x+this.i.x*a,this.o.y+this.i.y*a)}};Q.prototype.Aa=function(a){this.j||(this.C?this.C=!1:Y(this,y(C(a.dx,a.dy),this.i)))};
var Z=function(a,b){var c=a.getBoundingClientRect(),c=C(b.clientX-c.left,b.clientY-c.top),d=a.i,e=C(d.y,d.x),d=y(e,c),f=y(e,a.O),e=y(e,a.H);if(d<f||d>f+e)return null;d=a.i;c=y(d,c)-y(d,a.o)-y(d,a.O);d=Math.floor(c/a.A);return 0>d||d>=a.b||c%a.A>y(a.i,a.H)?null:d};g=Q.prototype;g.za=function(a){this.j||(this.stopRotation(),a=Z(this,a),null!=a&&H("frametap",this,{element:this.frames[a],id:a+1}))};
g.sa=function(a){(a=a.detail&&a.detail.id)&&(a=this.V[a-1])&&!H("frameexit",this,{url:a}).detail.handled&&window.open(a)};g.wa=function(){this.j||null==this.f||(H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),this.f=null)};g.ya=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&H("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};
g.ua=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&H("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};g.xa=function(a){this.j&&a.target.classList.contains("frame")&&H("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};g.va=function(a){this.j&&a.target.classList.contains("frame")&&H("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
g.ra=function(a){this.j&&a.target.classList.contains("frame")&&H("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};g.na=function(){if(0<this.h&&0<this.b)return Math.max(1,1+this.a-Math.floor((this.h-1)/2))};g.qa=function(){if(0<this.h&&0<this.b)return Math.min(this.b,1+this.a-Math.floor((this.h-1)/2)+this.h-1)};document.registerElement("gwd-swipegallery",{prototype:Q.prototype});}()
