-function(){"use strict";var f;var k=function(a,b){var c=parseInt(a.getAttribute("gwd-min-font-size-px"),10);isNaN(c)&&(c=b);return c},l=function(a,b){switch(a.getAttribute("gwd-fitting-truncate")){case "true":return!0;case "false":return!1;default:return b}};var p=/[^\s\xA0]/,r=function(a){return(a=q.exec(a||""))?parseFloat(a[1]):null},q=/^(\d+|\d*\.\d+)px$/i,t=/^(\d+|\d*\.\d+)em$/i;function x(){this.a=[];this.o=10;this.v=!1}
x.prototype.fit=function(a){var b=[];a.forEach(function(a){if(this.a.every(function(b){return b.element!=a})&&!a.hasAttribute("gwd-dont-fit")){y(a);var d=z(this,a);this.a.push(d);b.push(d)}},this);b.forEach(function(a){var b={originalFontSize:a.s,fittedFontSizePx:a.w,wasTruncated:null!=a.h};null!=a.h&&(b.originalInnerHTML=a.h);a=a.element;var e;b?(e=document.createEvent("CustomEvent"),e.initCustomEvent("gwdtextfitted",!0,!0,b)):(e=document.createEvent("Event"),e.initEvent("gwdtextfitted",!0,!0));
a.dispatchEvent(e)})};
var A=function(a,b){b.forEach(function(a){for(var b=0;b<this.a.length;b++){var e=this.a[b];if(e.element==a){e.element.style.fontSize=e.s;this.a.splice(b,1);break}}}.bind(a))},z=function(a,b){var c=window.getComputedStyle(b),d=r(c.fontSize)||24,e=k(b,a.o),h=l(b,a.v),c=b.style.fontSize,u=null;a:{for(var g=b.clientWidth,v=b.clientHeight;d>=e;d--)if(b.style.fontSize=""+d+"px",!(b.scrollHeight>v||b.scrollWidth>g)){e=d;break a}if(h){for(var u=b.innerHTML,h=b.textContent,d=h.length,m=1,w=0;10>w;w++){var n=
Math.floor((d+m)/2);b.innerHTML=h.slice(0,n)+"\u2026";b.scrollHeight>v||b.scrollWidth>g?d=n:m=n}b.innerHTML=h.slice(0,m)+"\u2026"}}return{element:b,s:c,w:e,h:u}},y=function(a){function b(a,c){a.hasAttribute("gwd-dont-fit")||Array.prototype.forEach.call(a.children,function(a){var d=window.getComputedStyle(a).fontSize,g=r(d);if(g)g!=c&&(d=g/c,a.style.fontSize=d+"em");else if(d=(g=t.exec(d||""))?parseFloat(g[1]):null)g=d*c;else return;b(a,g)})}var c=r(window.getComputedStyle(a).fontSize);null!=c&&b(a,
c)};var B=function(a){this.u=a;this.g=new WeakMap;this.j=new WeakMap};B.prototype.saveInitialText=function(a){for(var b=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),c=null,d;d=b.nextNode();)if(p.test(d.textContent)){c=d;break}if(c&&(b=c.parentNode,b!=a)){a.setAttribute("gwd-dont-fit","");for(c=b;c.parentNode!=a;)c=c.parentNode;this.g.set(a,{f:c,parent:b})}};
B.prototype.applyStylePreservation=function(a){if(this.g.get(a)){a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED||C(this,a);var b=document.createElement("gwd-attached");a.appendChild(b);var c=function(){b.removeEventListener("attached",c);C(this,a);a.removeChild(b)}.bind(this);b.addEventListener("attached",c)}};
var C=function(a,b){var c=a.g.get(b),d=a.j.get(b)||{};if(c){c.f.style.display="none";b.insertBefore(c.f,b.firstChild);try{A(a.u,[b]);var e=getComputedStyle(c.parent);D.forEach(function(a){var c=e.getPropertyValue(a);!d.hasOwnProperty(a)&&c&&b.style.setProperty(a,c,"")});b.removeAttribute("gwd-dont-fit");a.u.fit([b])}finally{b.removeChild(c.f)}}};B.prototype.saveStyleOverride=function(a,b,c){var d=this.j.get(a)||{};d[b]=c;this.j.set(a,d)};var D="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" ");var E=function(){};goog.inherits(E,HTMLElement);f=E.prototype;f.createdCallback=function(){this.c=new x;this.b=":not(*)";this.i=new B(this.c);this.C=this.B.bind(this);this.l=this.A.bind(this);document.addEventListener("pagetransitionstart",this.C);document.addEventListener("adinitialized",this.l);["fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"].forEach(this.m,this)};
f.A=function(a){"gwd-doubleclick"==a.target.tagName.toLowerCase()&&(document.removeEventListener("adinitialized",this.l),this.fit(Array.prototype.slice.call(document.querySelectorAll(this.b))))};f.B=function(a){"gwd-pagedeck"==a.target.getAttribute("is").toLowerCase()&&this.fit(Array.prototype.slice.call(a.target.querySelectorAll(this.b)))};f.saveInitialText=function(a){this.i.saveInitialText(a)};f.applyStylePreservation=function(a){this.i.applyStylePreservation(a)};
f.saveStyleOverride=function(a,b,c){this.i.saveStyleOverride(a,b,c)};f.m=function(a){var b=this.getAttribute(a);switch(a){case "fit-font-size-for-selector":this.b=b||":not(*)";break;case "gwd-min-font-size-px":this.c.o=k(this,10);break;case "gwd-fitting-truncate":this.c.v=l(this,!1)}};f.fit=function(a){this.c.fit(a||Array.prototype.slice.call(document.querySelectorAll(this.b)))};f.attributeChangedCallback=function(a){this.m(a)};document.registerElement("gwd-text-helper",{prototype:E.prototype});}()
